Proxy everywhere (except iframe) & fix minification
ZenithDevs/Kennel pull request #12
Opened 2021-01-20 14:01 UTC by relisiuol

2021-01-20 14:32 UTC, Shugabuga commented
The PR looks mostly good. I'll test it on my side later this week and look into merging.

However, there is one inconsistency: `DepictionVideoView` is proxied but video screenshots are not. I think @itss0n1c should give some feedback on whether we should be proxying video files or not.

2021-01-20 18:42 UTC, Shugabuga commented
Okay, I talked to other Zenith members for their feedback. We aren't planning on having Kennel support video proxying *quite yet*. If you think it'll be useful, maybe we can add it as an optional toggle in a future update, but the bandwidth cost on proxying videos (that aren't usually auto-loaded by the browser anyways) aren't worth it, while there is a clear benefit for proxying images (faster load from edge cache, easier to optimize for browser on server-side, and can reduce high-traffic stress to repos).

I'll annotate this on the PR, since it should be trivial to revert. Video caching in itself wouldn't be too hard to make optional though at a later date.

2021-01-20 18:50 UTC, Shugabuga requested changes
Seems solid. I'd just remove proxying for video links in `DepictionVideoView` (tl;dr it's less valuable than proxying images + I think that should be its own proxy URL) and it *should* be fine to merge!

Thanks for your contributions!

2021-01-20 18:50 UTC, Shugabuga commented on src/Kennel.ts
> +        videoURL = Kennel._laxSanitize(`${this.#proxyURL}${elem["URL"]}`);
Remove the reference to `${this.#proxyURL}` here. We don't want to have an image proxy also proxy video files.

Ideally, we can have this be another optional config property akin to `#proxyURL`, and you're more than welcome to implement it (say, `#videoProxyURL`). I may do so a future update; feel free to open an issue to remind me.

2021-01-20 18:50 UTC, Shugabuga commented on src/Kennel.ts
> +        ret += `<a class="nd_package nd_subtle_link" href="${pkgURL}">` +
At first, I was kinda skeptical about this because string concatenation, but good call here; the extra whitespace is annoying.

👍

2021-01-20 18:50 UTC, Shugabuga commented on src/Kennel.ts
> +            ssURL = Kennel._laxSanitize(`${this.#proxyURL}${elem["screenshots"][i]["url"]}`);
How did I miss this??? Thanks for this.

2021-01-20 18:50 UTC, Shugabuga commented on dist/Kennel.js
> +var _depiction,_proxyURL,_useShadowDom,_silenceErrors,_iframeHeader,_options,_tint,_packagePrefix,_defaultTint,_views,__classPrivateFieldSet=undefined&&undefined.__classPrivateFieldSet||function(e,i,
I'm assuming you just re-built with `rollup -c`, correct?

If not, do that.

2021-01-22 10:21 UTC, relisiuol commented on src/Kennel.ts
> +        videoURL = Kennel._laxSanitize(`${this.#proxyURL}${elem["URL"]}`);
Done.

2021-01-22 10:21 UTC, relisiuol commented on dist/Kennel.js
> +var _depiction,_proxyURL,_useShadowDom,_silenceErrors,_iframeHeader,_options,_tint,_packagePrefix,_defaultTint,_views,__classPrivateFieldSet=undefined&&undefined.__classPrivateFieldSet||function(e,i,
Correct.

2021-01-22 10:22 UTC, relisiuol commented
Proxy is now only for images.

2021-01-23 19:00 UTC, Shugabuga commented on src/Kennel.ts
> +        videoURL = Kennel._laxSanitize(`${this.#proxyURL}${elem["URL"]}`);
Thanks. I'll take a look at testing shortly.

2021-01-23 19:00 UTC, Shugabuga approved these changes

2021-01-26 21:26 UTC, Shugabuga commented
Sweet, tested and everything seems to work as intended! Merging! 🎉

2021-01-26 21:26 UTC, merged